const layouts={hand:['手账决策本','把推理、比较和结论写成一页手账'],terminal:['双区分析台','用终端视角查看约束、数据与判断'],magazine:['专题编辑部','用杂志叙事读懂完整答案'],ice:['ICE. 速览报','先看结论，再快速扫描关键证据'],minimal:['留白阅读页','去掉干扰，专注逻辑和行动清单'],app:['任务工作台','把答案变成可勾选、可调整的操作台'],neon:['数据驾驶舱','用指标与图表掌握决策重点']};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let plan,page,query='',active=-1,busy=false,checks=new Set();const pages=new Map(),checksets=new Map(),controls=new Map(),storeKey='liquid-web-v4';
const clip=(v,n)=>{const s=String(v||'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s};
function go(id){['start','selection','result'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));scrollTo(0,0)}
function save(){if(plan)localStorage.setItem(storeKey,JSON.stringify({plan,query,pages:Object.fromEntries(pages),checks:Object.fromEntries([...checksets].map(([k,v])=>[k,[...v]])),controls:Object.fromEntries(controls),active,showResult:!$('#result').classList.contains('hidden')}))}
function preview(layout,title){const [name]=layouts[layout];if(layout==='terminal')return `<div class="pv terminal-pv"><code>TASK_ANALYSIS_V2.0</code><i></i><i></i><b>▂▅▃▇▆</b></div>`;if(layout==='magazine')return `<div class="pv magazine-pv"><em>双<br>面<br>决<br>策</em><small>ISSUE 01</small></div>`;if(layout==='ice')return `<div class="pv ice-pv"><b>ICE.</b><small>NO. 01 / BRIEF</small></div>`;if(layout==='minimal')return `<div class="pv minimal-pv"><small>Answer · Focus</small><i></i><i></i></div>`;if(layout==='app')return `<div class="pv app-pv"><span>▣ 任务总览</span><div>✓ 核心结论　 <button>查看</button></div></div>`;if(layout==='neon')return `<div class="pv neon-pv"><b>✣</b><span>FACTS　◆◆◆<br>STATUS　READY</span></div>`;return `<div class="pv hand-pv"><b>📝 ${esc(clip(title||name,11))} ♥</b><small>#just for you</small><i></i></div>`}
function renderPlans(){if(!plan)return;$('#form-grid').innerHTML=plan.variants.map((v,i)=>{const meta=layouts[v.layout];return `<button class="form" data-variant="${i}" ${busy?'disabled':''}>${preview(v.layout,v.title)}<div class="form-meta"><b>${esc(meta[0])}</b><span>${esc(v.layout)}</span></div><div class="tags">${v.components.slice(0,3).map(x=>`<i>${esc(x)}</i>`).join('')}</div><p>${esc(clip(v.focus||meta[1],62))}</p><footer><span>${pages.has(i)?'● 已生成':'✦ 同一份答案'}</span><strong>${busy&&active===i?'生成中…':'立即进入 →'}</strong></footer></button>`}).join('')}
function factNote(ids=[]){const fs=(plan.sharedFacts||[]).filter(f=>ids.includes(f.id));if(!fs.length)return'';return `<details class="fact-note"><summary>🔎 依据与可信状态 · ${fs.length}</summary>${fs.map(f=>`<p><b>${f.kind==='user'?'用户提供':f.status==='verified'?'已验证':'待核实'}</b><span>${esc(f.statement)}</span>${f.source?`<small>${esc(f.source)}</small>`:''}</p>`).join('')}</details>`}
function table(rows,pick=false){if(!rows?.length)return'';return `<div class="table-scroll"><table><thead><tr>${rows[0].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map((r,i)=>`<tr ${pick?`tabindex="0" data-choice="${i}"`:''}>${r.map((x,j)=>`<td>${j===0?'<b>'+esc(x)+'</b>':esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${pick?'<p class="choice-result">点击一行，标记你的选择</p>':''}`}
function calculator(s,n){return `<div class="calculator" data-formula="${s.formula}" data-label="${esc(s.resultLabel)}">${s.fields.map((f,i)=>`<label><span>${esc(f.label)}</span><output>${f.value} ${esc(f.unit)}</output><input type="range" min="${f.min}" max="${f.max}" step="${f.step}" value="${f.value}" data-field="${n}-${i}" data-unit="${esc(f.unit)}"></label>`).join('')}<strong class="calc-result"></strong></div>`}
function chart(rows){if(!rows||rows.length<2)return'';const vals=rows.slice(1).map(r=>Number(r[1])||0),max=Math.max(1,...vals);return `<div class="bar-chart">${rows.slice(1).map((r,i)=>`<div><span>${esc(r[0])}</span><i style="--size:${Math.max(4,vals[i]/max*100)}%"></i><b>${esc(r[1])}</b></div>`).join('')}</div>`}
function section(s,n){let c='';if(['steps','timeline'].includes(s.type))c=`<ol class="steps ${s.type}">${s.items.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${esc(x)}</li>`).join('')}</ol>`;else if(s.type==='cards')c=`<div class="cards">${s.items.map((x,i)=>`<article><span>${['💡','🎯','✨','📌'][i%4]}</span>${esc(x)}</article>`).join('')}</div>`;else if(s.type==='table')c=table(s.rows);else if(s.type==='comparison')c=table(s.rows,true);else if(s.type==='barChart')c=chart(s.rows);else if(s.type==='calculator')c=calculator(s,n);else if(s.type==='checklist')c=`<div class="checklist">${s.items.map((x,j)=>`<label><input type="checkbox" data-check="${n}-${j}" ${checks.has(n+'-'+j)?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div>`;else c=`<ul class="narrative-list">${s.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;return `<section class="module type-${s.type}" id="module-${n}"><div class="module-heading"><span>${String(n+1).padStart(2,'0')}</span><h2>${esc(s.heading)}</h2></div><p class="module-intro">${esc(s.intro)}</p>${c}${factNote(s.factIds)}</section>`}
function updateCalc(){document.querySelectorAll('.calculator').forEach(box=>{const v=[...box.querySelectorAll('input')].map(x=>Number(x.value));const total=box.dataset.formula==='product'?v.reduce((a,b)=>a*b,1):v.reduce((a,b)=>a+b,0);box.querySelector('.calc-result').textContent=`${box.dataset.label||'计算结果'}：${Number(total.toFixed(2))}`})}
function show(){const v=plan.variants[active],mods=page.sections.map(section).join('');const chips=plan.constraints.slice(0,6).map(x=>`<i>${esc(x)}</i>`).join('');const nav=page.sections.map((s,i)=>`<a href="#module-${i}">${String(i+1).padStart(2,'0')} ${esc(s.heading)}</a>`).join('');$('#result').className='result theme-'+v.layout;$('#result').innerHTML=`<header class="result-toolbar"><button id="back" class="back">← 七种形态</button><span>${esc(layouts[v.layout][0])}</span><button id="fresh" class="back">新建 Query ＋</button></header><div class="paper"><div class="tape"></div><div class="hero"><p>✦ A Liquid Intelligent Page · just for you</p><h1>${esc(page.title)}</h1><h3>${esc(page.subtitle)}</h3><div class="constraint-chips">${chips}</div><blockquote>${esc(page.summary)}</blockquote></div><nav class="section-nav">${nav}</nav><div class="modules">${mods}</div><section class="closing"><h2>🤔 还在纠结？看这里</h2><div>${page.sections.slice(-1)[0].items.slice(0,3).map((x,i)=>`<article><span>${['🌡️','🎒','💡'][i]}</span>${esc(clip(x,70))}</article>`).join('')}</div><p>这份内容由 AI 根据你的 Query 实时生成。重要事实与价格请在行动前再次核实。</p></section></div>`;const state=controls.get(active)||{};document.querySelectorAll('.calculator input').forEach(input=>{if(state[input.dataset.field]!=null)input.value=state[input.dataset.field];input.previousElementSibling.value=`${input.value} ${input.dataset.unit}`});$('#back').onclick=()=>{go('selection');save()};$('#fresh').onclick=reset;$('#result').oninput=e=>{if(e.target.matches('.calculator input')){e.target.previousElementSibling.value=`${e.target.value} ${e.target.dataset.unit}`;controls.set(active,{...(controls.get(active)||{}),[e.target.dataset.field]:e.target.value});updateCalc();save()}};$('#result').onchange=e=>{const k=e.target.dataset.check;if(k){e.target.checked?checks.add(k):checks.delete(k);save()}};$('#result').onclick=e=>{const row=e.target.closest('[data-choice]');if(row)row.closest('.module').querySelector('.choice-result').textContent='✓ 当前选择：'+[...row.children].map(x=>x.textContent).join(' · ')};go('result');updateCalc();save()}
async function openVariant(i){if(busy||!plan?.variants[i])return;active=i;$('#plan-error').textContent='';if(!pages.has(i)){busy=true;renderPlans();try{const r=await fetch('/api/page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:plan.sessionId,variantIndex:i}),signal:AbortSignal.timeout(110000)}),d=await r.json();if(!r.ok)throw Error(d.error||'生成失败');for(let n=0;n<7;n++)pages.set(n,d)}catch(e){$('#plan-error').textContent=e.name==='TimeoutError'?'生成时间较长，请再次点击重试。':e.message}finally{busy=false;renderPlans()}}if(pages.has(i)){page=pages.get(i);checks=checksets.get(i)||new Set();checksets.set(i,checks);show()}}
function reset(){localStorage.removeItem(storeKey);plan=page=null;query='';active=-1;pages.clear();checksets.clear();controls.clear();$('#query').value='';go('start')}
$('#form-grid').onclick=e=>{const b=e.target.closest('[data-variant]');if(b)openVariant(Number(b.dataset.variant))};$('#new-query').onclick=reset;
$('#query-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const q=$('#query').value.trim();if(!q)return;busy=true;$('#generate').disabled=true;$('#error').textContent='';$('#generate').textContent='正在理解需求与组织统一答案…';try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q}),signal:AbortSignal.timeout(110000)}),d=await r.json();if(!r.ok)throw Error(d.error||'生成失败');plan=d;query=q;pages.clear();$('#selection-title').textContent=plan.title;$('#selection-query').textContent=q;renderPlans();go('selection');save()}catch(e){$('#error').textContent=e.name==='TimeoutError'?'服务响应较慢，请再试一次。':e.message}finally{busy=false;$('#generate').disabled=false;$('#generate').textContent='✦ 让 AI 生成专属网页'}};
async function restore(){let s;try{s=JSON.parse(localStorage.getItem(storeKey))}catch{}if(!s?.plan?.sessionId)return;query=s.query||'';$('#query').value=query;try{const r=await fetch('/api/session/'+encodeURIComponent(s.plan.sessionId)),fresh=await r.json();if(!r.ok)throw Error();plan={...fresh};delete plan.pages;Object.entries({...s.pages,...fresh.pages}).forEach(([k,v])=>pages.set(Number(k),v));Object.entries(s.checks||{}).forEach(([k,v])=>checksets.set(Number(k),new Set(v)));Object.entries(s.controls||{}).forEach(([k,v])=>controls.set(Number(k),v));$('#selection-title').textContent=plan.title;$('#selection-query').textContent=query;renderPlans();if(s.showResult&&pages.has(s.active)){active=s.active;page=pages.get(active);checks=checksets.get(active)||new Set();show()}else go('selection')}catch{$('#error').textContent='上次方案已过期，原 Query 已为你保留，请重新生成。';localStorage.removeItem(storeKey);go('start')}}
fetch('/api/health').then(r=>r.json()).then(s=>{$('#connection').textContent=s.ready?'● 模型已连接 · 内容统一 · 七种形态':'请先配置模型密钥'}).catch(()=>{$('#connection').textContent='服务正在唤醒，首次打开可能需要约一分钟'});restore();
